[project]
name = "gemini-markdown"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-genai>=1.2.0",
    "httpx>=0.28.1",
    "pathlib>=1.0.1",
    "python-dotenv>=1.0.1",
]
